### ISSUE TITLE
Information for replicating this project.

### ISSUE THREAD

**Issue by Limon93** [openthermalcamera/HW-Firmware#1]
Hi, 
I am really interested in making your fantastic project (it is so well built that i want one) but i need some help to understand some missing information.

First: Pcb thickness to match edge usb c connector. 
I downloaded the step file for the connector and found that the maximum thickness for the pcb should be 0.8mm, is this correct?

Second: Code compiling and uploading. 
I assume this project is written in the Atollic Truestudio IDE. I compiled and obtained an hex file for the stm32 chip. The build analyzer reported around 98% or ram used and around 52% flash used for the chip. Are those values coherent with your builds? I am asking this just to be sure my build came out well. Then, to upload the hex to the board, i need an swd debugger, a j-link programmer or something else? I am new to the swd interface.

Thank for the project and the support.
Simone.

**Comment by themarpe** [comment]
Hi Limon93. Thanks for your kind words.

PCB thickness is indeed 0.8mm. Thanks for pointing this out, will add this information to PCB repository.

Yes, this sounds coherent. Will also do some updates on the firmware repository soon, so watch out for a release (will include needed hex, elf & dfu files).

To flash the firmware the easiest way to do is, after you've assembled the board, to plug it in the PC and flash it using the STs DfuSe tool. As the blank stm32f042 chip will boot in DFU bootloader. If PC is not an option, there also exists a "android-stm32-dfu-programmer" by UmbrelaSmart.
[Github repository](https://github.com/UmbrelaSmart/android-stm32-dfu-programmer)

If you stumble upon any problem, don't hesitate to write back.
Best regards,
Martin

**Comment by Limon93** [comment]
Thanks for the fast and helpful response Martin, i will close this issue. 
Waiting for parts and pcb. 
Keep it up.

Simone.
